"""add_analytics_table

Revision ID: 2026_01_05_111332
Revises: 2026_01_01_231956
Create Date: 2026-01-05 11:13:34.974798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_05_111332'
down_revision: Union[str, Sequence[str], None] = '2026_01_01_231956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evm_events',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('transaction_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('tx_gas_used', sa.BigInteger(), nullable=True),
    sa.Column('tx_effective_gas_price', sa.Numeric(), nullable=True),
    sa.Column('tx_value', sa.Numeric(), nullable=False),
    sa.Column('tx_from_address', postgresql.BYTEA(), nullable=False),
    sa.Column('tx_to_address', postgresql.BYTEA(), nullable=True),
    sa.Column('contract_address', postgresql.BYTEA(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'transaction_hash', 'log_index'),
    schema='analytics'
    )
    op.create_index('ix_analytics_events_chain_contract_event_block', 'evm_events', ['chain_id', 'contract_address', 'event_name', 'block_number'], unique=False, schema='analytics')
    op.create_index('ix_analytics_events_chain_tx', 'evm_events', ['chain_id', 'transaction_hash'], unique=False, schema='analytics')
    op.drop_index(op.f('txs_block_idx'), table_name='transactions', schema='raw')
    op.drop_table('transactions', schema='raw')
    op.drop_index(op.f('logs_block_idx'), table_name='logs', schema='raw')
    op.drop_table('logs', schema='raw')
    op.drop_index(op.f('receipts_block_idx'), table_name='receipts', schema='raw')
    op.drop_table('receipts', schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('block_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('block_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('transaction_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('to', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('contract_address', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gas_used', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cumulative_gas_used', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('effective_gas_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('logs_bloom', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'transaction_hash', name=op.f('receipts_pk')),
    schema='raw'
    )
    op.create_index(op.f('receipts_block_idx'), 'receipts', ['chain_id', 'block_number'], unique=False, schema='raw')
    op.create_table('logs',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('block_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('transaction_hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('log_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('topic0', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('topic1', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('topic2', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('topic3', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('removed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'transaction_hash', 'log_index', name=op.f('logs_pk')),
    schema='raw'
    )
    op.create_index(op.f('logs_block_idx'), 'logs', ['chain_id', 'block_number'], unique=False, schema='raw')
    op.create_table('transactions',
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hash', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('block_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('block_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('transaction_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('to', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('gas', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('gas_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('max_fee_per_gas', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('max_priority_fee_per_gas', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('input', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('nonce', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('v', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('r', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('s', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('y_parity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_list', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'hash', name=op.f('txs_pk')),
    schema='raw'
    )
    op.create_index(op.f('txs_block_idx'), 'transactions', ['chain_id', 'block_number'], unique=False, schema='raw')
    op.drop_index('ix_analytics_events_chain_tx', table_name='evm_events', schema='analytics')
    op.drop_index('ix_analytics_events_chain_contract_event_block', table_name='evm_events', schema='analytics')
    op.drop_table('evm_events', schema='analytics')
    # ### end Alembic commands ###
