"""add_evm_event_logs_table

Revision ID: 2026_01_01_231956
Revises: 
Create Date: 2026-01-01 23:19:57.673836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_01_231956'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS staging")

    op.create_table('evm_event_logs',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('transaction_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('tx_from', postgresql.BYTEA(), nullable=False),
    sa.Column('tx_to', postgresql.BYTEA(), nullable=True),
    sa.Column('tx_value', sa.Numeric(), nullable=False),
    sa.Column('tx_type', sa.SmallInteger(), nullable=True),
    sa.Column('tx_status', sa.SmallInteger(), nullable=True),
    sa.Column('tx_gas_used', sa.BigInteger(), nullable=True),
    sa.Column('tx_cumulative_gas_used', sa.BigInteger(), nullable=True),
    sa.Column('tx_effective_gas_price', sa.Numeric(), nullable=True),
    sa.Column('address', postgresql.BYTEA(), nullable=False),
    sa.Column('topic0', postgresql.BYTEA(), nullable=True),
    sa.Column('topic1', postgresql.BYTEA(), nullable=True),
    sa.Column('topic2', postgresql.BYTEA(), nullable=True),
    sa.Column('topic3', postgresql.BYTEA(), nullable=True),
    sa.Column('data', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'block_number', 'log_index'),
    schema='staging'
    )
    op.create_index('ix_logs_chain_address_topic0_block', 'evm_event_logs', ['chain_id', 'address', 'topic0', 'block_number'], unique=False, schema='staging')
    op.create_index('ix_logs_chain_txhash', 'evm_event_logs', ['chain_id', 'transaction_hash'], unique=False, schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_chain_txhash', table_name='evm_event_logs', schema='staging')
    op.drop_index('ix_logs_chain_address_topic0_block', table_name='evm_event_logs', schema='staging')
    op.drop_table('evm_event_logs', schema='staging')
    # ### end Alembic commands ###
