"""add-timestamp-to-wallet-swaps

Revision ID: 2026_01_21_232141
Revises: 2026_01_19_203916
Create Date: 2026-01-21 23:21:45.603865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_01_21_232141'
down_revision: Union[str, Sequence[str], None] = '2026_01_19_203916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uniswap_v4_wallet_swaps', sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False), schema='domain')
    op.create_index('ix_uni_v4_swaps_wallet_time', 'uniswap_v4_wallet_swaps', ['wallet_address', 'block_timestamp'], unique=False, schema='domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uni_v4_swaps_wallet_time', table_name='uniswap_v4_wallet_swaps', schema='domain')
    op.drop_column('uniswap_v4_wallet_swaps', 'block_timestamp', schema='domain')
    # ### end Alembic commands ###
