"""add_blocks_table

Revision ID: 2026_01_06_140126
Revises: 2026_01_05_122031
Create Date: 2026-01-06 14:01:29.001227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_06_140126'
down_revision: Union[str, Sequence[str], None] = '2026_01_05_122031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('parent_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_fee_per_gas', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('gas_limit', sa.BigInteger(), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'block_number'),
    schema='analytics'
    )
    op.create_index('ix_analytics_blocks_chain_hash', 'blocks', ['chain_id', 'block_hash'], unique=False, schema='analytics')
    op.create_index('ix_analytics_blocks_chain_timestamp', 'blocks', ['chain_id', 'timestamp'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_blocks_chain_timestamp', table_name='blocks', schema='analytics')
    op.drop_index('ix_analytics_blocks_chain_hash', table_name='blocks', schema='analytics')
    op.drop_table('blocks', schema='analytics')
    # ### end Alembic commands ###
