"""add_uniswap_v4_wallet_swaps

Revision ID: 2026_01_16_212529
Revises: 2026_01_16_203614
Create Date: 2026-01-16 21:25:30.833091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_16_212529'
down_revision: Union[str, Sequence[str], None] = '2026_01_16_203614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS domain")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uniswap_v4_wallet_swaps',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('transaction_hash', postgresql.BYTEA(), nullable=False),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('wallet_address', postgresql.BYTEA(), nullable=False),
    sa.Column('pool_manager', postgresql.BYTEA(), nullable=False),
    sa.Column('pool_id', postgresql.BYTEA(), nullable=False),
    sa.Column('sender', postgresql.BYTEA(), nullable=True),
    sa.Column('recipient', postgresql.BYTEA(), nullable=True),
    sa.Column('amount0', sa.Numeric(), nullable=False),
    sa.Column('amount1', sa.Numeric(), nullable=False),
    sa.Column('sqrt_price_x96', sa.Numeric(), nullable=True),
    sa.Column('liquidity', sa.Numeric(), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('event_signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chain_id', 'transaction_hash', 'log_index'),
    schema='domain'
    )
    op.create_index('ix_uni_v4_swaps_chain_pool_order', 'uniswap_v4_wallet_swaps', ['chain_id', 'pool_id', 'block_number', 'transaction_index', 'log_index'], unique=False, schema='domain')
    op.create_index('ix_uni_v4_swaps_chain_tx', 'uniswap_v4_wallet_swaps', ['chain_id', 'transaction_hash'], unique=False, schema='domain')
    op.create_index('ix_uni_v4_swaps_chain_wallet_order', 'uniswap_v4_wallet_swaps', ['chain_id', 'wallet_address', 'block_number', 'transaction_index', 'log_index'], unique=False, schema='domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uni_v4_swaps_chain_wallet_order', table_name='uniswap_v4_wallet_swaps', schema='domain')
    op.drop_index('ix_uni_v4_swaps_chain_tx', table_name='uniswap_v4_wallet_swaps', schema='domain')
    op.drop_index('ix_uni_v4_swaps_chain_pool_order', table_name='uniswap_v4_wallet_swaps', schema='domain')
    op.drop_table('uniswap_v4_wallet_swaps', schema='domain')
    # ### end Alembic commands ###
