"""add-pools-and-tokens-tables

Revision ID: 2026_01_27_095808
Revises: 2026_01_21_232141
Create Date: 2026-01-27 09:58:12.409509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_27_095808'
down_revision: Union[str, Sequence[str], None] = '2026_01_21_232141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('token_address', postgresql.BYTEA(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'token_address'),
    schema='domain'
    )
    op.create_index('ix_tokens_chain_symbol', 'tokens', ['chain_id', 'symbol'], unique=False, schema='domain')
    op.create_table('uniswap_v4_pools',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', postgresql.BYTEA(), nullable=False),
    sa.Column('pool_manager', postgresql.BYTEA(), nullable=False),
    sa.Column('token0_address', postgresql.BYTEA(), nullable=False),
    sa.Column('token1_address', postgresql.BYTEA(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('tick_spacing', sa.Integer(), nullable=True),
    sa.Column('hooks', postgresql.BYTEA(), nullable=True),
    sa.Column('created_block', sa.BigInteger(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'pool_id'),
    schema='domain'
    )
    op.create_index('ix_uni_v4_pools_chain_manager', 'uniswap_v4_pools', ['chain_id', 'pool_manager'], unique=False, schema='domain')
    op.create_index('ix_uni_v4_pools_chain_tokens', 'uniswap_v4_pools', ['chain_id', 'token0_address', 'token1_address'], unique=False, schema='domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uni_v4_pools_chain_tokens', table_name='uniswap_v4_pools', schema='domain')
    op.drop_index('ix_uni_v4_pools_chain_manager', table_name='uniswap_v4_pools', schema='domain')
    op.drop_table('uniswap_v4_pools', schema='domain')
    op.drop_index('ix_tokens_chain_symbol', table_name='tokens', schema='domain')
    op.drop_table('tokens', schema='domain')
    # ### end Alembic commands ###
