"""add-event-signatures-table

Revision ID: 2026_01_05_122031
Revises: 2026_01_05_111332
Create Date: 2026-01-05 12:20:34.736442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_05_122031'
down_revision: Union[str, Sequence[str], None] = '2026_01_05_111332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_signatures',
    sa.Column('topic0', postgresql.BYTEA(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('topic0'),
    schema='analytics'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_signatures', schema='analytics')
    # ### end Alembic commands ###
